import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:dotted_border/dotted_border.dart';

import '../../../breast_cancer_for_normal/presentation/widgets/breast_check_history/note_description.dart';
import '../widgets/box_content.dart';
import '../widgets/image.dart';
import '../widgets/add_and_show_result_button.dart';

import '../providers/for_doctor_screen_state_provider.dart';
import '../widgets/styled_text.dart';

class ForDoctorsScreen extends StatelessWidget {
  const ForDoctorsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final screenSize = MediaQuery.of(context).size;
    final isportrait =
        MediaQuery.of(context).orientation == Orientation.portrait;
    final shapeHeight = screenSize.width * (isportrait ? 0.30 : 0.13);

    final provider = Provider.of<ForDoctorScreenState>(context);

    return Scaffold(
      backgroundColor: Colors.transparent,
      body: ListView(
        padding: EdgeInsets.symmetric(vertical: shapeHeight),
        children: [
          const SizedBox(height: 10),
          const StyledText(
            text:
                "Pick a Medical Image of Breast Cancer Radiology (X-Ray) or Histology of The Patient.",
          ),
          const SizedBox(height: 15),
          const StyledText(
            text:
                "See The Result OR Prediction Using The Machine Learning Model.",
          ),
          const SizedBox(height: 30),
          Align(
            child: DottedBorder(
              borderType: BorderType.RRect,
              radius: const Radius.circular(10),
              padding: EdgeInsets.zero,
              color: const Color.fromRGBO(112, 112, 112, 0.40),
              dashPattern: const [7, 7],
              child: Container(
                width: screenSize.width,
                height: screenSize.width * 0.65,
                constraints: const BoxConstraints(
                  maxWidth: 450,
                  maxHeight: 450 * 0.5,
                ),
                padding: const EdgeInsets.all(1),
                decoration: BoxDecoration(
                  color: const Color.fromRGBO(112, 112, 112, 0.25),
                  borderRadius: BorderRadius.circular(10),
                ),
                child: provider.fileImage != null
                    ? ImageFromFile(imagePath: provider.fileImage!.path)
                    : provider.networkImage != null
                        ? ImageFromNetwork(imageUrl: provider.networkImage!)
                        : const BoxContent(),
              ),
            ),
          )
              .animate(target: provider.isBoxShown ? 1 : 0)
              // .move(begin: Offset(-100, -100), end: Offset(0, 0))
              .scaleXY(begin: 0, end: 1, duration: 250.ms)
              .fade(begin: 0, end: 1),
          const SizedBox(height: 20),
          const AddAndShowResultButton(),
          const SizedBox(height: 20),
          NoteDescription(
            icon: Icon(
              Icons.warning_rounded, // FontAwesomeIcons.triangleExclamation,
              size: 50,
              color: Colors.red.shade900,
            ).animate(
              onPlay: (controller) {
                controller.loop(count: 6, reverse: true);
              },
            ).scaleXY(begin: 1, end: 1.2, duration: 500.ms),
            title: "Caution",
            description:
                "This AI model is a tool for assisting medical professionals and should only be used by trained specialists. "
                "It is not a substitute for expert medical judgment, diagnosis, or treatment. \n\n"
                "Please be aware that the predictions made by this model are not 100 percent accurate, and they should not be solely relied upon for making medical decisions. "
                "Always consult with a qualified healthcare provider or breast cancer specialist for a comprehensive evaluation and diagnosis. \n\n"
                "Using this model without expert oversight may lead to incorrect conclusions and potentially harmful outcomes. Your health and well-being are of utmost importance, "
                "and this AI model is meant to complement, not replace, the expertise of medical professionals. \n\n"
                "Please exercise caution and discretion when interpreting the results generated by this AI model and seek the guidance of a qualified healthcare professional for any concerns related to breast cancer or your overall health.",
          ),
          const SizedBox(height: 5),
        ],
      ),
    );
  }
}
