// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIZc3u2t2N5jeRXXIV6bmYFMYuzAr_6Bo',
    appId: '1:583240425126:web:658f000a39ae9a7dec5e67',
    messagingSenderId: '583240425126',
    projectId: 'breast-cancer-awareness-9b69e',
    authDomain: 'breast-cancer-awareness-9b69e.firebaseapp.com',
    storageBucket: 'breast-cancer-awareness-9b69e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8gFD8mNat8OmASthgiFm9bdmc9aE2Y0Q',
    appId: '1:583240425126:android:5d811900f0c937c2ec5e67',
    messagingSenderId: '583240425126',
    projectId: 'breast-cancer-awareness-9b69e',
    storageBucket: 'breast-cancer-awareness-9b69e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYrfaqJc8OH4ytuyayt4V8pYXNK9972uA',
    appId: '1:583240425126:ios:6915548a4b69aea0ec5e67',
    messagingSenderId: '583240425126',
    projectId: 'breast-cancer-awareness-9b69e',
    storageBucket: 'breast-cancer-awareness-9b69e.appspot.com',
    iosBundleId: 'com.salahalshafey.breastcancerawareness',
  );
}
