// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX2NLQ5wt1wfoteZYrfE6zG84w8ePEHrs',
    appId: '1:996856719448:web:6af69f15bc5730562dc22d',
    messagingSenderId: '996856719448',
    projectId: 'breast-cancer-awareness-bf348',
    authDomain: 'breast-cancer-awareness-bf348.firebaseapp.com',
    storageBucket: 'breast-cancer-awareness-bf348.appspot.com',
    measurementId: 'G-X6PP6NBK2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWMPvnC_mKXomXZnouDeC7ayC5pnKp5Jw',
    appId: '1:996856719448:android:7798c22d3e83a5f02dc22d',
    messagingSenderId: '996856719448',
    projectId: 'breast-cancer-awareness-bf348',
    storageBucket: 'breast-cancer-awareness-bf348.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPy2aC8RvspQ3zg0BpbHkuk3mSF3hBOWs',
    appId: '1:996856719448:ios:aac2f3ad5ef166bc2dc22d',
    messagingSenderId: '996856719448',
    projectId: 'breast-cancer-awareness-bf348',
    storageBucket: 'breast-cancer-awareness-bf348.appspot.com',
    iosBundleId: 'com.salahalshafey.breastcancerawareness',
  );
}
